# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3073a30b5d865feb70ea95f21372e78ba0eeb2fcdf4d5d6ce0ceaaa1828645d01eb6ccdc63d3209cd0f842ea30d823005486fab032cc9d831ca3ec67d28eff0
  month_gap : 0

test:
  secret_key_base: cbb75cb24be579c313ed356900f5df76d8b1a75d4ba74cec23ef25b52a274bac592acf8f3b4001fbcddc61b607fc5b9e8934a3d1db228151359702a471b7a709
  month_gap : 1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  month_gap : 1