SearchType.create(searchtext: 'Biggest price increase')
SearchType.create(searchtext: 'Biggest price decrease')
SearchType.create(searchtext: 'Newest Additions')
SearchType.create(searchtext: 'Just Sold')
SearchType.create(searchtext: "Historic Avg")
SearchType.create(searchtext: "Historic Min")
SearchType.create(searchtext:'Volume Sales')
SearchType.create(searchtext:'Volume Summary Property Types')
SearchType.create(searchtext:'Sold Summary Prop Type')