# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Waringstown',  county:'Co.Armagh')
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Donaghcloney', county:'Co.Armagh')
#SearchType.create(searchtext: 'Biggest price increase')
#SearchType.create(searchtext: 'Biggest price decrease')
#SearchType.create(searchtext: 'Newest Additions')
#SearchType.create(searchtext: 'Just Sold')
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Aghagallon',  county:'Co.Antrim')
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Aghalee',  county:'Co.Antrim')
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ahoghill',  county:'Co.Antrim')
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Aldergrove',  county:'Co.Antrim')
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Antrim',  county:'Co.Antrim')
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Armoy',  county:'Co.Antrim')
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Aughafatten',  county:'Co.Antrim')
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballintoy',  county:'Co.Antrim')
#SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballybogy',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballycarry',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballycastle',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballyclare',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballycraigy',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballyeaston',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballygalley',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballyhenry',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballylinney',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballymacash',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballymena',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballymoney',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballynure',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballyrobert',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballystrudder',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Ballyvoy',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Balnamore',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Barmeen',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Belfast	',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Bendooragh',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Broomhedge',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Broughshane',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Buckna',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Bushmills',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Capecastle',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Cargan',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Carnalbanagh',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Carncastle',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Carnlough',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Carnmoney',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Carrickfergus',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Clogh',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Cloughmills',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Cogry-Kilbride',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Connor',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Craigarogan',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Crumlin',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Cullybackey',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Cushendall',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Cushendun',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Dervock',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Derrymore',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Doagh',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Donegore',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Drains Bay',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Drumlough',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Dunadry',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Dunamuggy',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Dundrod',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Dunloy',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Dunmurry',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Dunseverick',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Galgorm Parks',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Gawleys Gate',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Glenarm',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Glenavy',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Glengormley',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Glenoe',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Glynn',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Gracehill',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Grange Corner',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Greenisland',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Groggan',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Jordanstown',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Kells-Connor',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Kellswater',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Keshbridge',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Killead',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Knocknacarry',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Lambeg',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Larne',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Lisburn',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Lisnagarvey',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Longkesh',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Loughguile',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Loughlynch',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Lower Ballinderry',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Lower Broomhedge',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Lurganure',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Lurganville',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Maghaberry',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Magheramorne',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Martinstown',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Maze',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Mill Bay',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Millbank',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Milltown',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Moneyglass',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Monkstown',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Moss-Side',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Mounthill',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Mullaghboy',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Newtown Crommelin',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Newtownabbey',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Parkgate',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Portballintrae',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Portbraddon',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Portglenone',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Portrush',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Randalstown',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Rasharkin',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Rathcoole',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Roughfort',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Solar',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Stoneyford',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Straid',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Stranocum',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Templepatrick',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Tobergill',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Toome',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Tullynacross',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Upper Ballinderry',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Waterfoot',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Whiteabbey',  county:'Co.Antrim')
SearchParams.create(searchtitle: 'N.Ireland', searchparam:'Whitehead',  county:'Co.Antrim')
